#
# Makefile for the led aw9106 driver.
#

# Each configuration option enables a list of files.

obj-m += zte_led.o

zte_led-objs := leds-aw22xxx.o

BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/zte_led.ko

